/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import DAO.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modele.*;

/**
 *
 * @author Daniel
 */
public class Requete extends javax.swing.JFrame {

    /**
     * Creates new form Requete
     */
    public Requete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        PanelLecture1 = new javax.swing.JScrollPane();
        table_aff1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        BoutonRecherMalade = new javax.swing.JToggleButton();
        LabelChoix4 = new javax.swing.JLabel();
        T1_M = new javax.swing.JTextField();
        LabelChoix5 = new javax.swing.JLabel();
        T2_M = new javax.swing.JTextField();
        LabelChoix6 = new javax.swing.JLabel();
        T3_M = new javax.swing.JTextField();
        T4_M = new javax.swing.JTextField();
        LabelChoix7 = new javax.swing.JLabel();
        T5_M = new javax.swing.JTextField();
        LabelChoix16 = new javax.swing.JLabel();
        LabelChoix17 = new javax.swing.JLabel();
        T6_M = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        PanelLecture = new javax.swing.JScrollPane();
        table_aff = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        BoutonRecherService = new javax.swing.JToggleButton();
        LabelChoix = new javax.swing.JLabel();
        BoutonAff = new javax.swing.JButton();
        T1 = new javax.swing.JTextField();
        LabelChoix2 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        LabelChoix1 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        LabelChoix3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        PanelLecture2 = new javax.swing.JScrollPane();
        table_aff2 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        BoutonSuppr2 = new javax.swing.JToggleButton();
        LabelChoix8 = new javax.swing.JLabel();
        T1_I = new javax.swing.JTextField();
        LabelChoix9 = new javax.swing.JLabel();
        T2_I = new javax.swing.JTextField();
        LabelChoix10 = new javax.swing.JLabel();
        T3_I = new javax.swing.JTextField();
        T4_I = new javax.swing.JTextField();
        LabelChoix11 = new javax.swing.JLabel();
        T5_I = new javax.swing.JTextField();
        LabelChoix18 = new javax.swing.JLabel();
        LabelChoix19 = new javax.swing.JLabel();
        T6_I = new javax.swing.JTextField();
        LabelChoix20 = new javax.swing.JLabel();
        T7_I = new javax.swing.JTextField();
        LabelChoix21 = new javax.swing.JLabel();
        Button1 = new javax.swing.JRadioButton();
        Button3 = new javax.swing.JRadioButton();
        Button2 = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        PanelLecture3 = new javax.swing.JScrollPane();
        table_aff3 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        BoutonSuppr3 = new javax.swing.JToggleButton();
        LabelChoix12 = new javax.swing.JLabel();
        BoutonAff3 = new javax.swing.JButton();
        T13 = new javax.swing.JTextField();
        LabelChoix13 = new javax.swing.JLabel();
        T14 = new javax.swing.JTextField();
        LabelChoix14 = new javax.swing.JLabel();
        T15 = new javax.swing.JTextField();
        T16 = new javax.swing.JTextField();
        LabelChoix15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1041, 751));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        table_aff1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PanelLecture1.setViewportView(table_aff1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(PanelLecture1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLecture1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8);

        BoutonRecherMalade.setText("Rechercher");
        BoutonRecherMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRecherMaladeActionPerformed(evt);
            }
        });

        LabelChoix4.setText("Numero :");

        T1_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1_MActionPerformed(evt);
            }
        });

        LabelChoix5.setText("Nom :");

        T2_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2_MActionPerformed(evt);
            }
        });

        LabelChoix6.setText("Prenom :");

        T3_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3_MActionPerformed(evt);
            }
        });

        T4_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4_MActionPerformed(evt);
            }
        });

        LabelChoix7.setText("Tel :");

        T5_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5_MActionPerformed(evt);
            }
        });

        LabelChoix16.setText("Adresse :");

        LabelChoix17.setText("Mutuelle :");

        T6_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6_MActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonRecherMalade, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(LabelChoix4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T1_M)
                    .addComponent(LabelChoix5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T2_M, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelChoix6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T3_M, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T4_M)
                    .addComponent(LabelChoix7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T5_M)
                    .addComponent(LabelChoix16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelChoix17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T6_M))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelChoix4)
                .addGap(8, 8, 8)
                .addComponent(T1_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T3_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T4_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T5_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix17, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T6_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BoutonRecherMalade)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9);
        jPanel9.getAccessibleContext().setAccessibleName("Malade");

        jTabbedPane1.addTab("Malade", jPanel7);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        table_aff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PanelLecture.setViewportView(table_aff);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(PanelLecture, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLecture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        BoutonRecherService.setText("Rechercher");
        BoutonRecherService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRecherServiceActionPerformed(evt);
            }
        });

        LabelChoix.setText("Code :");

        BoutonAff.setText("Afficher");
        BoutonAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAffActionPerformed(evt);
            }
        });

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });

        LabelChoix2.setText("Nom :");

        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });

        LabelChoix1.setText("Batiment :");

        T3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3ActionPerformed(evt);
            }
        });

        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });

        LabelChoix3.setText("Directeur :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonRecherService, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(LabelChoix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoutonAff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T1)
                    .addComponent(LabelChoix2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelChoix1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T4)
                    .addComponent(LabelChoix3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelChoix)
                .addGap(8, 8, 8)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BoutonRecherService)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addComponent(BoutonAff)
                .addContainerGap())
        );

        jPanel4.add(jPanel6);

        jTabbedPane1.addTab("Service", jPanel4);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        table_aff2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PanelLecture2.setViewportView(table_aff2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(PanelLecture2, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLecture2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11);

        BoutonSuppr2.setText("Rechercher");
        BoutonSuppr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSuppr2ActionPerformed(evt);
            }
        });

        LabelChoix8.setText("Numero :");

        T1_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1_IActionPerformed(evt);
            }
        });

        LabelChoix9.setText("Nom :");

        T2_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2_IActionPerformed(evt);
            }
        });

        LabelChoix10.setText("Prenom :");

        T3_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3_IActionPerformed(evt);
            }
        });

        T4_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4_IActionPerformed(evt);
            }
        });

        LabelChoix11.setText("Adresse :");

        T5_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5_IActionPerformed(evt);
            }
        });

        LabelChoix18.setText("Tel :");

        LabelChoix19.setText("Code Service :");

        T6_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6_IActionPerformed(evt);
            }
        });

        LabelChoix20.setText("Rotation :");

        T7_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T7_IActionPerformed(evt);
            }
        });

        LabelChoix21.setText("Salaire :");

        Button1.setText("< 1000 €");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setText(" > 1500 €");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button2.setText("Entre 1000 et 1500€");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonSuppr2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(LabelChoix8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T1_I)
                    .addComponent(LabelChoix9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T2_I, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelChoix10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T3_I, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T4_I)
                    .addComponent(LabelChoix11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T5_I)
                    .addComponent(LabelChoix18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelChoix19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T6_I)
                    .addComponent(LabelChoix20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T7_I)
                    .addComponent(LabelChoix21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button2)
                            .addComponent(Button3)
                            .addComponent(Button1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelChoix8)
                .addGap(8, 8, 8)
                .addComponent(T1_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T3_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T4_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T5_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T6_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T7_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button3)
                .addGap(37, 37, 37)
                .addComponent(BoutonSuppr2)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel12);

        jTabbedPane1.addTab("Infirmier", jPanel10);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        table_aff3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PanelLecture3.setViewportView(table_aff3);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(PanelLecture3, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLecture3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel14);

        BoutonSuppr3.setText("Rechercher");
        BoutonSuppr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSuppr3ActionPerformed(evt);
            }
        });

        LabelChoix12.setText("Code :");

        BoutonAff3.setText("Afficher");
        BoutonAff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAff3ActionPerformed(evt);
            }
        });

        T13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T13ActionPerformed(evt);
            }
        });

        LabelChoix13.setText("Nom :");

        T14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T14ActionPerformed(evt);
            }
        });

        LabelChoix14.setText("Batiment :");

        T15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T15ActionPerformed(evt);
            }
        });

        T16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T16ActionPerformed(evt);
            }
        });

        LabelChoix15.setText("Directeur :");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonSuppr3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(LabelChoix12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoutonAff3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T13)
                    .addComponent(LabelChoix13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelChoix14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T16)
                    .addComponent(LabelChoix15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelChoix12)
                .addGap(8, 8, 8)
                .addComponent(T13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChoix15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BoutonSuppr3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addComponent(BoutonAff3)
                .addContainerGap())
        );

        jPanel13.add(jPanel15);

        jTabbedPane1.addTab("Service", jPanel13);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void T3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void BoutonAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonAffActionPerformed

    private void BoutonRecherServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRecherServiceActionPerformed
        // TODO add your handling code here:
        ServiceDAO servDAO = new ServiceDAO();
        ArrayList tab;
        String[] title;
        DefaultTableModel tableModel = new DefaultTableModel(0, 0);

        String code = T1.getText();
        String nom = T2.getText();
        String batiment = T3.getText();
        String directeur = T4.getText();
        String req = "SELECT * FROM service "
        + "WHERE code LIKE '" + code + "%' "
        + "AND nom LIKE '" + nom + "%' "
        + "AND batiment LIKE '" + batiment +"%' ";;

        if(!directeur.equals(""))
        {
            req = req + "AND directeur = " + directeur;
        }
        //récupération de toutes lignes d'une table, chacune stockée dans un objet, et stockage dans un tableau
        tab = servDAO.requete(req);
        //création des titres des colonnes
        title = new String[]{"Code", "Nom", "Batiment", "Directeur"};
        tableModel.setColumnIdentifiers(title);
        //pour chaque objet dans le tableau, on récupère les informations et on les ajoutes sur une nouvelle ligne du JTable
        for (int i = 0; i < tab.size(); i++)
        {
            Service elem = (Service) tab.get(i);
            Object obj[] = {
                elem.getCode(),
                elem.getNom(),
                elem.getBatiment(),
                elem.getDirecteur(),
            };
            tableModel.addRow(obj);
        }

        table_aff.setModel(tableModel);
        PanelLecture.setViewportView(table_aff);
    }//GEN-LAST:event_BoutonRecherServiceActionPerformed

    private void BoutonRecherMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRecherMaladeActionPerformed
        // TODO add your handling code here:
        MaladeDAO maladeDAO = new MaladeDAO();
        ArrayList tab;
        String[] title;
        DefaultTableModel tableModel = new DefaultTableModel(0, 0);

        String numero = T1_M.getText();
        String nom = T2_M.getText();
        String prenom = T3_M.getText();
        String tel = T4_M.getText();
        String adresse = T5_M.getText();
        String mutuelle = T6_M.getText();
        String req = "SELECT * FROM malade "
        + "WHERE nom LIKE '" + nom + "%' "
        + "AND prenom LIKE '" + prenom + "%' "
        + "AND adresse LIKE '" + adresse + "%' "
        + "AND tel LIKE '" + tel + "%' "
        + "AND mutuelle LIKE '" + mutuelle +"%' ";

        if(!numero.equals(""))
        {
            req = req + "AND numero = " + numero;
        }
        //récupération de toutes lignes d'une table, chacune stockée dans un objet, et stockage dans un tableau
        tab = maladeDAO.requete(req);
        //création des titres des colonnes
        title = new String[]{"Numero", "Nom", "Prenom", "Adresse", "Tel", "Mutuelle"};
        tableModel.setColumnIdentifiers(title);
        //pour chaque objet dans le tableau, on récupère les informations et on les ajoutes sur une nouvelle ligne du JTable
        for (int i = 0; i < tab.size(); i++)
        {
            Malade elem = (Malade) tab.get(i);
            Object obj[] = {
                    elem.getNumero(),
                    elem.getNom(),
                    elem.getPrenom(),
                    elem.getAdresse(),
                    elem.getTel(),
                    elem.getMutuelle(),
                    elem.getTab_docteur(),
                    };
            tableModel.addRow(obj);
        }

        table_aff1.setModel(tableModel);
        PanelLecture1.setViewportView(table_aff1);
    }//GEN-LAST:event_BoutonRecherMaladeActionPerformed

    private void T1_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1_MActionPerformed

    private void T2_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2_MActionPerformed

    private void T3_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3_MActionPerformed

    private void T4_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4_MActionPerformed

    private void BoutonSuppr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSuppr2ActionPerformed
        // TODO add your handling code here:
        InfirmierDAO infirmierDAO = new InfirmierDAO();
        ArrayList tab;
        String[] title;
        DefaultTableModel tableModel = new DefaultTableModel(0, 0);

        String numero = T1_I.getText();
        String nom = T2_I.getText();
        String prenom = T3_I.getText();
        String tel = T4_I.getText();
        String adresse = T5_I.getText();
        String code = T6_M.getText();
        String rotation = T7_I.getText();
        String req = "SELECT * FROM employe e,infirmier i WHERE e.numero = i.numero "
        + "AND e.nom LIKE '" + nom + "%' "
        + "AND e.prenom LIKE '" + prenom + "%' "
        + "AND e.adresse LIKE '" + adresse + "%' "
        + "AND e.tel LIKE '" + tel + "%' "
        + "AND i.code_service LIKE '" + code +"%' "
        + "AND i.rotation LIKE '" + rotation + "%' ";

        if(!numero.equals(""))
        {
            req = req + "AND numero = " + numero;
        }
        else if(Button1.isSelected())
        {
            System.out.print("TEST");
            req = req + "AND i.salaire < 1000 ";
        }
        else if(Button2.isSelected())
        {
            req = req + "AND i.salaire BETWEEN 1000 AND 1500";
        }
        else if(Button3.isSelected())
        {
            req = req + "AND i.salaire > 1500";
        }
        //récupération de toutes lignes d'une table, chacune stockée dans un objet, et stockage dans un tableau
        tab = infirmierDAO.requete(req);
        //création des titres des colonnes
       title = new String[]{"Numero", "Nom", "Prenom", "Telephone", "Adresse", "Code Service", "Rotation", "Salaire"};
        tableModel.setColumnIdentifiers(title);
        //pour chaque objet dans le tableau, on récupère les informations et on les ajoutes sur une nouvelle ligne du JTable
        for (int i = 0; i < tab.size(); i++)
        {
            Infirmier elem = (Infirmier) tab.get(i);
            Object obj[] = {
                    elem.getNumero(),
                    elem.getNom(),
                    elem.getPrenom(),
                    elem.getTel(),
                    elem.getAdresse(),
                    elem.getCode_service(),
                    elem.getRotation(),
                    elem.getSalaire(),
                    };
            tableModel.addRow(obj);
        }

        table_aff2.setModel(tableModel);
        PanelLecture2.setViewportView(table_aff2);
    }//GEN-LAST:event_BoutonSuppr2ActionPerformed

    private void T1_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1_IActionPerformed

    private void T2_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2_IActionPerformed

    private void T3_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3_IActionPerformed

    private void T4_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4_IActionPerformed

    private void BoutonSuppr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSuppr3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonSuppr3ActionPerformed

    private void BoutonAff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAff3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonAff3ActionPerformed

    private void T13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T13ActionPerformed

    private void T14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T14ActionPerformed

    private void T15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T15ActionPerformed

    private void T16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T16ActionPerformed

    private void T5_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5_MActionPerformed

    private void T6_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T6_MActionPerformed

    private void T5_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5_IActionPerformed

    private void T6_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T6_IActionPerformed

    private void T7_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T7_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T7_IActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
        Button1.setSelected(false);
        Button2.setSelected(false);
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
         Button1.setSelected(false);
         Button3.setSelected(false);
      
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        Button2.setSelected(false);
        Button3.setSelected(false);
    }//GEN-LAST:event_Button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAff;
    public javax.swing.JButton BoutonAff3;
    private javax.swing.JToggleButton BoutonRecherMalade;
    private javax.swing.JToggleButton BoutonRecherService;
    private javax.swing.JToggleButton BoutonSuppr2;
    private javax.swing.JToggleButton BoutonSuppr3;
    private javax.swing.JRadioButton Button1;
    private javax.swing.JRadioButton Button2;
    private javax.swing.JRadioButton Button3;
    private javax.swing.JLabel LabelChoix;
    private javax.swing.JLabel LabelChoix1;
    private javax.swing.JLabel LabelChoix10;
    private javax.swing.JLabel LabelChoix11;
    private javax.swing.JLabel LabelChoix12;
    private javax.swing.JLabel LabelChoix13;
    private javax.swing.JLabel LabelChoix14;
    private javax.swing.JLabel LabelChoix15;
    private javax.swing.JLabel LabelChoix16;
    private javax.swing.JLabel LabelChoix17;
    private javax.swing.JLabel LabelChoix18;
    private javax.swing.JLabel LabelChoix19;
    private javax.swing.JLabel LabelChoix2;
    private javax.swing.JLabel LabelChoix20;
    private javax.swing.JLabel LabelChoix21;
    private javax.swing.JLabel LabelChoix3;
    private javax.swing.JLabel LabelChoix4;
    private javax.swing.JLabel LabelChoix5;
    private javax.swing.JLabel LabelChoix6;
    private javax.swing.JLabel LabelChoix7;
    private javax.swing.JLabel LabelChoix8;
    private javax.swing.JLabel LabelChoix9;
    private javax.swing.JScrollPane PanelLecture;
    private javax.swing.JScrollPane PanelLecture1;
    private javax.swing.JScrollPane PanelLecture2;
    private javax.swing.JScrollPane PanelLecture3;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T13;
    private javax.swing.JTextField T14;
    private javax.swing.JTextField T15;
    private javax.swing.JTextField T16;
    private javax.swing.JTextField T1_I;
    private javax.swing.JTextField T1_M;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T2_I;
    private javax.swing.JTextField T2_M;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T3_I;
    private javax.swing.JTextField T3_M;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T4_I;
    private javax.swing.JTextField T4_M;
    private javax.swing.JTextField T5_I;
    private javax.swing.JTextField T5_M;
    private javax.swing.JTextField T6_I;
    private javax.swing.JTextField T6_M;
    private javax.swing.JTextField T7_I;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table_aff;
    public javax.swing.JTable table_aff1;
    public javax.swing.JTable table_aff2;
    public javax.swing.JTable table_aff3;
    // End of variables declaration//GEN-END:variables
}
